### ISSUE TITLE
Missing PHP GD LIbrary Extension

### ISSUE THREAD

**Issue by anderaith** [Hyzual/docker-koel#26] opened 2020-07-05 17:25 UTC
Hello, 

I'm using your docker image of koel and I'm unable to get the images of the albums and artists to appear.
After some troubleshooting, it seems that that feature need the PHP GD extension to work.
It seems to be missing from this image last release.

Laravel log: 
[2020-07-05 16:03:26] production.ERROR: Intervention\Image\Exception\NotSupportedException: GD Library extension not available with this PHP installation. in /var/www/html/vendor/intervention/image/src/Inter
vention/Image/Gd/Driver.php:19

I tried to modify the Dockerfile to get it installed but I was unable to do so.

Regards,
Pierre-Yves Bouvier

**Comment by Hyzual** [comment] 2020-07-06 16:17
Hi, thanks for the report.
There is a pending contribution at #25 to add GD as a dependency. When I've tested it and it's merged, a new docker image will be pushed including it.

**Comment by Hyzual** [comment] 2020-07-06 21:38
#25 has been merged and the new image has been pushed. From the tests I've made, it looks like the covers appear correctly. Could you confirm if the problem is fixed on your side after pulling the new image ?

**Comment by anderaith** [comment] 2020-07-07 03:58
The problem is fixed.
It works perfectly now. Thank you.

**Comment by Hyzual** [comment] 2020-07-07 06:57
Glad to hear it :smile:. Thanks to @bastidest for the fix !

**Closed by Hyzual** 2020-07-07 06:57 UTC
